### Sample Dataset

In [3]:
import pandas as pd

sensus = {'tinggi': [158, 170, 183, 191, 155, 163, 180, 158, 170], 
          'jk': ['pria', 'pria', 'pria', 'pria', 'wanita', 'wanita', 'wanita', 'wanita', 'wanita'],
          'berat': [64, 86, 84, 80, 49, 59, 67, 54, 67]}

sensus_df = pd.DataFrame(sensus)
sensus_df

tinggi      jk  berat
0     158    pria     64
1     170    pria     86
2     183    pria     84
3     191    pria     80
4     155  wanita     49
5     163  wanita     59
6     180  wanita     67
7     158  wanita     54
8     170  wanita     67

### Regresion Dengan KNN

In [4]:
import numpy as np

X_train = np.array(sensus_df[['tinggi', 'jk']])
y_train = np.array(sensus_df['berat'])

print('X_train:',X_train)
print('y_train:',y_train)

X_train: [[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]
y_train: [64 86 84 80 49 59 67 54 67]


### Preprocess Dataset

In [5]:
X_train_transposed = np.transpose(X_train)

print(f'X_train:\n{X_train}\n')
print(f'X_train_transposed:\n{X_train_transposed}')

X_train:
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]

X_train_transposed:
[[158 170 183 191 155 163 180 158 170]
 ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita'
  'wanita']]


In [6]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
jk_binarised = lb.fit_transform(X_train_transposed[1])

print('jk:',X_train_transposed[1])
print('jk_binarised:',jk_binarised)

jk: ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita' 'wanita']
jk_binarised: [[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [7]:
jk_binarised = jk_binarised.flatten()
jk_binarised

array([0, 0, 0, 0, 1, 1, 1, 1, 1])

In [8]:
X_train_transposed[1] = jk_binarised
X_train = X_train_transposed.transpose()

print('X_train_transposed:',X_train_transposed)
print('X_train:',X_train)

X_train_transposed: [[158 170 183 191 155 163 180 158 170]
 [0 0 0 0 1 1 1 1 1]]
X_train: [[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [170 1]]


### Training KNN Regresion model

In [9]:
from sklearn.neighbors import KNeighborsRegressor

K = 3
model = KNeighborsRegressor(n_neighbors=K)
model.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=3)

In [10]:
X_new = np.array([[155, 1]])
X_new

array([[155,   1]])

In [11]:
y_pred = model.predict(X_new)
y_pred

array([55.66666667])

### Evaluasi KNN Regresion model

In [12]:
X_test = np.array([[168, 0], [180, 0], [160, 1], [169, 1]])
y_test = np.array([65, 96, 52, 67])

print('X_test:',X_test)
print('y_test: ',y_test)

X_test: [[168   0]
 [180   0]
 [160   1]
 [169   1]]
y_test:  [65 96 52 67]


In [13]:
y_pred = model.predict(X_test)
y_pred

array([70.66666667, 79.        , 59.        , 70.66666667])

### Coefficient of determination

In [14]:
from sklearn.metrics import r2_score

r_squared = r2_score(y_test, y_pred)

print(f'R-squared: {r_squared}')


R-squared: 0.6290565226735438


### Mean Absolute Eror

In [15]:
from sklearn.metrics import mean_absolute_error

MAE = mean_absolute_error(y_test, y_pred)

print(f'MAE: {MAE}')

MAE: 8.333333333333336


### Mean Squared Eror

In [16]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y_test, y_pred)

print(f'MSE: {MSE}')

MSE: 95.8888888888889


### Masalah Scaling

In [17]:
from scipy.spatial.distance import euclidean

# tinggi dalam milimeter
X_train = np.array([[1700, 0], [1600, 1]])
X_new = np.array([[1640, 0]])

[euclidean(X_new[0], d) for d in X_train]

[60.0, 40.01249804748511]

In [18]:
X_train = np.array([[1.7, 0], [1.6, 1]])
X_new = np.array([[1.64, 0]])

[euclidean(X_new[0], d) for d in X_train]

[0.06000000000000005, 1.0007996802557442]

### Standard Scaler

In [19]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

In [20]:
X_train = np.array([[1700, 0], [1600, 1]])
X_train_scaled = ss.fit_transform(X_train)
print('X_train_scaled:', X_train_scaled)

X_new = np.array([[1640, 0]])
X_new_scaled = ss.transform(X_new)
print('X_new_scaled: ',X_new_scaled)

jarak = [euclidean(X_new_scaled[0], d) for d in X_train_scaled]
print('jarak: ',jarak)

X_train_scaled: [[ 1. -1.]
 [-1.  1.]]
X_new_scaled:  [[-0.2 -1. ]]
jarak:  [1.2, 2.1540659228538015]


In [21]:
X_train = np.array([[1.7, 0], [1.6, 1]])
X_train_scaled = ss.fit_transform(X_train)
print('X_train_scaled:', X_train_scaled)

X_new = np.array([[1.64, 0]])
X_new_scaled = ss.transform(X_new)
print('X_new_scaled: ',X_new_scaled)

jarak = [euclidean(X_new_scaled[0], d) for d in X_train_scaled]
print('jarak: ',jarak)

X_train_scaled: [[ 1. -1.]
 [-1.  1.]]
X_new_scaled:  [[-0.2 -1. ]]
jarak:  [1.2000000000000026, 2.1540659228538006]


### Featurees Scaling

In [22]:
X_train = np.array([[158, 0], [170, 0], [183, 0], [191, 0], [155, 1], [163, 1],
                    [180, 1], [158, 1], [170, 1]])

y_train = np.array([64, 86, 84, 80, 49, 59, 67, 54, 67])


X_test = np.array([[168, 0], [180, 0], [160, 1], [169, 1]])
y_test = np.array([65, 96, 52, 67])

### Standard Scaller

In [23]:
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

print('X_train_scaled:',X_train_scaled)
print('X_test_scaled:',X_test_scaled)

X_train_scaled: [[-0.9908706  -1.11803399]
 [ 0.01869567 -1.11803399]
 [ 1.11239246 -1.11803399]
 [ 1.78543664 -1.11803399]
 [-1.24326216  0.89442719]
 [-0.57021798  0.89442719]
 [ 0.86000089  0.89442719]
 [-0.9908706   0.89442719]
 [ 0.01869567  0.89442719]]
X_test_scaled: [[-0.14956537 -1.11803399]
 [ 0.86000089 -1.11803399]
 [-0.82260955  0.89442719]
 [-0.06543485  0.89442719]]


### Training Evaluasi Model

In [24]:
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

MAE = mean_absolute_error(y_test, y_pred)
MSE = mean_squared_error(y_test, y_pred)

print(f'MAE: {MAE}')
print(f'MSE: {MSE}')

MAE: 7.583333333333336
MSE: 85.13888888888893
